---
title: Maggie Germano | Financial Coach based in Washington, DC
timezone: America/New_York
collections:
  audience-logos:
    title: Audience Logos
    output: true
  categories:
    title: Categories
    output: true
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true
    future: false
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
  events:
    title: events
    output: true
    permalink: "/events/:path/"
  other-events:
    title: other-events
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    image: "/uploads/featuredimage.png"
    is-menu: 
- scope:
    path: ''
    type: events
  values:
    layout: event
    title: 
    image: 
    og-image: 
    sm-image: 
    event-date: 
    start-time: 
    end-time: 
    location: 
    button-text: Sign Me Up
    button-link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JF9KN58RCEPEC
    is-money-circle: 'true'
    ticket-price: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    image: 
    author: Maggie Germano
    author-desc: 'Certified Financial Education Instructor. Feminist and financial
      coach for women. Founder of Money Circle. '
    author-image: "/uploads/maggie_author.jpg"
    tweet: " "
    posts:
    - 
    - 
    - 
    comments: true
    future: false
- scope:
    path: ''
    type: categories
  values:
    color: 
- scope:
    path: ''
    type: testimonials
  values:
    image: 
permalink: pretty
gems:
- jekyll-paginate
- jekyll-sitemap
paginate: 5
paginate_path: "/blog/page:num/"
email: boss@maggiegermano.com
description: Break the taboo of discussing debt, earnings, and financial goals. Shake
  the feeling of anxiety and confusion when it comes to money. Learn the tools to
  take control of your finances, prepare for the future, and achieve your dreams.
url: https://maggiegermano.com
twitter_username: maggiegermano
github_username: DanRader
port: 6689
google-analytics: |-
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-77261410-1', 'auto');
    ga('send', 'pageview');
  </script>
